#!/bin/bash
command=$1
arguments=""
for arg in "$@"; do
  arguments="$arguments $arg"
done
arguments=`echo $arguments | cut -d" " --complement -f1`
if [ "$command" = "list" ]; then
	apt list
elif [ "$command" = "search" ]; then
	apt search $2
elif [ "$command" = "show" ]; then
	apt show $2
elif [ "$command" = "install" ]; then
	package=$arguments
	allpackages="$package"
	packagenum=0
	dlsize=0
	installsize=0
	alldependencies=`apt-cache depends --recurse --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances $package | grep "^\w" | sort -u | cut -d: -f1`
	alliterations=`echo $alldependencies | wc -w`
	rm -rf ./debs
	rm -rf ./dd
	mkdir debs
	mkdir dd
	cd debs
	iteration=0
	tput sc
	printf "Analyse des dépendances (0/$alliterations)"
	for dependence in $alldependencies; do
		isdependenceinstalled=`dpkg-query --list | grep -i "$dependence"`
		iteration=`expr $iteration + 1`
		tput rc;tput el
		printf "Analyse des dépendances ($iteration/$alliterations)"
		if [ "$isdependenceinstalled" = "" ]; then
			allpackages="$allpackages $dependence"
      packagenum=`expr $packagenum + 1`
		fi
	done
	pkgdlsize=`apt-cache show --no-all-versions $allpackages | grep ^Size | cut -d':' -f2 | xargs`
	pkginstallsize=`apt-cache show --no-all-versions $allpackages | grep ^Installed-Size | cut -d':' -f2 | xargs`
  for num in $pkgdlsize; do
    dlsize=`expr $num + $dlsize`
  done
  for num in $pkginstallsize; do
    installsize=`expr $num + $installsize`
  done
	dlsize=`expr $dlsize / 1048576`
	installsize=`expr $installsize / 1024`
	echo ""
	echo "Les paquets suivants seront installés :"
	echo "$allpackages"
	echo "$packagenum paquets à installer."
	echo "Il est nécessaire de prendre $dlsize Mo dans les archives."
	echo "Après cette opération, $installsize Mo d'espace disque supplémentaire seront utilisés."
	read -p "Souhaitez-vous continuer ? [O/n] " acceptInstall
	if [ "$acceptInstall" = "" ] || [ "$acceptInstall" = "O" ] || [ "$acceptInstall" = "o" ]; then
		apt download $package $dependencies
		cd ..
		for f in `ls -C debs/`; do
			dpkg-deb -x debs/$f ./dd/
		done
		cp dd/usr/* -r ~/.local/
		ln -s $HOME/.local/games/* $HOME/.local/bin/
		rm -rf ./debs > /dev/null
		rm -rf ./dd > /dev/null
	else
		cd ..
		echo "Annulation."
		rm -rf ./debs > /dev/null
		rm -rf ./dd > /dev/null
	fi
elif [ "$command" = "remove" ]; then
	package=$arguments
  packagenum=`echo $package | wc -w`
	rm -rf ./debs
	rm -rf ./dd
	mkdir debs
	mkdir dd
	cd debs
	echo "Les paquets suivants seront désinstallés :"
	echo "$package"
	echo "$packagenum paquets à désinstaller."
	read -p "Souhaitez-vous continuer ? [O/n] " acceptInstall
	if [ "$acceptInstall" = "" ] || [ "$acceptInstall" = "O" ] || [ "$acceptInstall" = "o" ]; then
		apt download $package
		cd ..
		for f in `ls -C debs/`; do
			dpkg-deb -x debs/$f ./dd/
		done
		cd dd/usr
		for f in `find */* -print`; do
			rm -rf $HOME/.local/$f
		done
		cd ../..
		rm -rf ./debs > /dev/null
		rm -rf ./dd > /dev/null
	else
		cd ..
		echo "Annulation."
		rm -rf ./debs > /dev/null
		rm -rf ./dd > /dev/null
	fi
elif [ "$command" = "portable-upgrade" ]; then
  echo "Upgrading portableapt..."
  wget -qO - https://github.com/DocSystem/portableapt/raw/main/upgrade | bash -
  echo "portableapt was successfully upgraded"
else
	echo "portableapt 0.3b (all)"
	echo "Usage : portableapt commande"
	echo ""
	echo "portableapt est un outil en ligne de commande pour gérer les paquets."
	echo "Il fournit des commandes pour chercher et gérer autant que pour"
	echo "rechercher des informations à propos des paquets. Il fournit les mêmes"
	echo "fonctions que les outils APT spécialisés, tels qu'apt-get et apt-cache,"
	echo "mais dispose d'options plus adaptées pour une utilisation interactive."
	echo "portableapt permet d'executer les commandes d'apt sans droits d'administrateur"
	echo ""
	echo "Commandes les plus utilisées :"
  echo "  list - liste les paquets selon leur nom (utilise apt)"
  echo "  search - cherche dans les descriptions de paquet (utilise apt)"
  echo "  show - affiche les détails du paquet (utilise apt)"
  echo "  install - installe / réinstalle / met à jour un paquet"
  echo "  remove - supprime des paquets"
  echo "  portable-upgrade - met à jour le portableapt depuis GitHub"
fi
