#!/bin/bash
if test -f $HOME/.local/bin/portableapt; then
  rm -f $HOME/.local/bin/portableapt
fi
echo "Installation de Portable APT..."
mkdir -p $HOME/.local/{bin,games,lib}
wget -q -O $HOME/.local/bin/portableapt https://github.com/DocSystem/portableapt/raw/main/portableapt
chmod +x $HOME/.local/bin/portableapt
if [[ ":$PATH:" == *":$HOME/.local/bin:"* ]]; then
  echo "Le dossier des executables utilisateurs est déjà dans le PATH !"
else
  echo "Le dossier des executables utilisateurs n'est pas dans le PATH, ajout en cours..."
  export PATH="$HOME/.local/bin:$PATH"
  echo "Le dossier des executables utilisateurs est maintenant dans le PATH !"
echo "Portable APT est prêt !"
fi
