#!/bin/bash
echo "Setting up Portable APT..."
mkdir -p $HOME/.local/{bin,games,lib}
wget -q -O $HOME/.local/bin/portableapt https://github.com/DocSystem/portableapt/raw/main/portableapt
chmod +x $HOME/.local/bin/portableapt
echo "Portable APT is now ready\!"
echo "On some operating systems, you will need to restart your session for changes to take effect, or at least restart terminal"
