#!/bin/bash
if test -f $HOME/.local/bin/portableapt; then
  rm -f $HOME/.local/bin/portableapt
fi
echo "Installation de Portable APT..."
mkdir -p $HOME/.local/{bin,games,lib}
wget -q -O $HOME/.local/bin/portableapt https://github.com/DocSystem/portableapt/raw/main/portableapt
chmod +x $HOME/.local/bin/portableapt
echo "Ajout de Portable APT au PATH !"
if test -f $HOME/.bashrc; then
  echo "PATH=$HOME/.local/bin:\$PATH" >> $HOME/.bashrc
else if test -f $HOME/.zshrc; then
  echo "PATH=$HOME/.local/bin:\$PATH" >> $HOME/.zshrc
fi
echo "Portable APT est prêt !"
fi
